# Generated by Django 5.2.8 on 2025-12-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="phote",
            new_name="photo",
        ),
    ]
